name: CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  IMAGE_NAME: portfolio

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from ref
        id: extract-version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_ACCOUNT: ${{ secrets.ACCOUNT }}
          envkey_APPPASSWORD: ${{ secrets.APPPASSWORD }}
          envkey_RECEIVER: ${{ secrets.RECEIVER }}
      
      - name: Docker build
        run: docker build -t $IMAGE_NAME .

      - name: Docker login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin ${{ secrets.REGISTRY_HOST }}

      - name: Push to Docker registry
        run: |
          FULL_IMAGE_NAME="${{ secrets.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}:${{ steps.extract-version.outputs.version }}"
          docker tag $IMAGE_NAME $FULL_IMAGE_NAME
          docker push $FULL_IMAGE_NAME
